	AREA NPR, CODE
	;AREA NCR.CODE
N RN 1
R RN 2
DIVIDEND RN 3
DIVISOR RN 4
	MOV N,#7
	MOV R,#3
LOOP
	MOV R5,N
	BL FACT
	MOV DIVIDEND,R6
	;MOV R5,R ; Include this statment for Ncr
	;BL FACT ; Include this statment for Ncr
	;MOV DIVISOR,R6 ; Include this statment for Ncr
	SUB R7,N,R
	MOV R5,R7
	BL FACT
	;MUL DIVISOR,R6,DIVISOR ; For NCR
	MOV DIVISOR , R6 ; Delete this line for NCR
	BL DIV
GO B GO
FACT
	MOV R6,#1
FACTLOOP
	MUL R6,R5,R6
	SUBS R5,R5,#1
	BNE FACTLOOP
	MOV PC, LR
DIV
	MOV R8,#0
SUBAGAIN
	SUBS DIVIDEND,DIVIDEND,DIVISOR
	ADDPL R8,R8,#1
	BPL SUBAGAIN
	MOV PC,LR
	END
